global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-metrics'
    static_configs:
      - targets: ['kafka-1:9101']
  
  - job_name: 'jmx-exporter'
    static_configs:
      - targets: ['jmx-exporter:9404']
